using CatalogService.Core;
using CatalogService.Core.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace CatalogService.WebApi.Controllers
{
	[Route("api/[controller]")]
	[ApiController]
	public class CategoriesController : ControllerBase
	{
		ICategoryService categoryService;

		public CategoriesController(ICategoryService categoryService)
		{
			this.categoryService = categoryService;
		}

		/// <summary>
		/// Lists categories.
		/// </summary>
		/// <returns>List of category models</returns>
		/// <response code="200">Request was performed successfully.</response>
		[HttpGet]
		[ProducesResponseType(StatusCodes.Status200OK)]
		public async Task<ActionResult<IEnumerable<CategoryDto>>> List()
		{
			return Ok(await categoryService.ListAsync());
		}

		/// <summary>
		/// Gets category info.
		/// </summary>
		/// <param name="id">Category id</param>
		/// <returns>Category model</returns>
		/// <response code="200">Request was performed successfully.</response>
		/// <response code="400">If id is not a positive value</response>
		[HttpGet("{id}")]
		[ProducesResponseType(StatusCodes.Status200OK)]
		[ProducesResponseType(StatusCodes.Status400BadRequest)]
		public async Task<ActionResult<CategoryDto>> Get(int id)
		{
			if (id <= 0)
			{
				return BadRequest();
			}

			return Ok(await categoryService.GetAsync(id));
		}

		/// <summary>
		/// Adds new category.
		/// </summary>
		/// <param name="category">Category model to add</param>
		/// <returns></returns>
		/// <response code="201">Request was performed successfully.</response>
		/// <response code="400">If category model is invalid</response>
		[HttpPost]
		[ProducesResponseType(StatusCodes.Status201Created)]
		[ProducesResponseType(StatusCodes.Status400BadRequest)]
		public async Task<IActionResult> Post([FromBody] CategoryDto category)
		{
			if (category == null || 
				category.Id > 0 || // Id must be generated by the system
				string.IsNullOrEmpty(category.Name))
			{
				return BadRequest();
			}

			var added = await categoryService.AddAsync(category);
			return CreatedAtAction(nameof(Get), new { id = added?.Id }, added);
		}

		/// <summary>
		/// Updates existing category.
		/// </summary>
		/// <param name="id">Id of a category to update</param>
		/// <param name="category">Category model to update</param>
		/// <returns></returns>
		/// <response code="200">Request was performed successfully.</response>
		/// <response code="400">If category model is invalid or id is not a positive value</response>
		[HttpPut("{id}")]
		[ProducesResponseType(StatusCodes.Status200OK)]
		[ProducesResponseType(StatusCodes.Status400BadRequest)]
		public async Task<IActionResult> Put(int id, [FromBody] CategoryDto category)
		{
			if (category == null || 
				id <= 0 ||
				category.Id != id ||
				string.IsNullOrEmpty(category.Name))
			{
				return BadRequest();
			}

			await categoryService.UpdateAsync(category);
			return Ok();
		}

		/// <summary>
		/// Deletes category and all associated products.
		/// </summary>
		/// <param name="id">Id of a category to delete</param>
		/// <returns></returns>
		/// <response code="204">Request was performed successfully.</response>
		/// <response code="400">If id is not a positive value</response>
		[HttpDelete("{id}")]
		[ProducesResponseType(StatusCodes.Status204NoContent)]
		[ProducesResponseType(StatusCodes.Status400BadRequest)]
		public async Task<IActionResult> Delete(int id, [FromServices] IProductService productService)
		{
			if (id <= 0)
			{
				return BadRequest();
			}

			var productsInCategory = await productService.ListAsync(id);
			foreach (var product in productsInCategory)
			{
				await productService.DeleteAsync(product.Id);
			}
			await categoryService.DeleteAsync(id);
			return NoContent();
		}
	}
}
